Repository CapstoneDesign-2022/FindDict-Server, pull requests merged in 2022-11, with the labels that each got.

#19 Feat: 단어 상세조회#18
  package-lock.json
  package.json
  src/controllers/WordController.ts
  src/interfaces/IWord.ts
  src/modules/responseMessage.ts
  src/routes/WordRouter.ts
  src/services/WordService.ts
  yarn.lock
Labels: GET🔮

#22 [FIX] accessToken 만료 기한 연장
  src/modules/jwtHandler.ts
Labels: Fix🛠

#24 [FIX] 로그인 요청 방식 변경
  src/controllers/UserController.ts
  src/routes/UserRouter.ts
Labels: Fix🛠

#26 Fix: 존재하지 않는 유저ID 접근오류#25
  src/services/UserService.ts
Labels: Fix🛠

#9 Feat: 이미지 불러오기
  src/config/index.ts
  src/controllers/WordController.ts
  src/modules/responseMessage.ts
  src/routes/WordRouter.ts
  src/routes/index.ts
  src/services/WordService.ts
  src/services/index.ts
Labels: Enhancement⭐

#28 Fix: 아이디중복 post->get 변경#27
  src/controllers/UserController.ts
  src/interfaces/IUser.ts
  src/services/UserService.ts
Labels: Fix🛠

#31 Fix: 아이디중복 오류수정
  src/controllers/UserController.ts
  src/services/UserService.ts
Labels: Fix🛠

#32 Fix: 단어 db 변경에 따른 api 수정
  src/controllers/WordController.ts
  src/interfaces/IWord.ts
  src/routes/WordRouter.ts
  src/services/WordService.ts
  yarn.lock
Labels: documentation
